name: CD

on:
    push:
        branches:
            - main
            - dev

env:
    REGISTRY: reg.m1000.fr
    IMAGE_NAME: leserveur/lebot

jobs:
    release:
        runs-on: self-hosted
        permissions:
            contents: write
            issues: write
            pull-requests: write
        outputs:
            version: ${{ steps.get_version.outputs.VERSION }}
            released: ${{ steps.semantic_release.outputs.new_release_published }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set HOME
              run: echo "HOME=$RUNNER_TEMP" >> $GITHUB_ENV

            - name: Fix git safe directory
              run: |
                  git config --global --add safe.directory "$GITHUB_WORKSPACE"
                  git config --global --add safe.directory '*'

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run Semantic Release
              id: semantic_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  bunx semantic-release --no-ci
                  echo "new_release_published=true" >> $GITHUB_OUTPUT

            - name: Get version from package.json
              id: get_version
              if: steps.semantic_release.outputs.new_release_published == 'true'
              run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

    build:
        needs: release
        if: ${{ needs.release.outputs.released == 'true' && github.ref == 'refs/heads/main' }}
        runs-on: self-hosted
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set HOME
              run: echo "HOME=$RUNNER_TEMP" >> $GITHUB_ENV

            - name: Fix git safe directory
              run: git config --global --add safe.directory '*'

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Update package.json version
              run: |
                  npm version ${{ needs.release.outputs.version }} --no-git-tag-version
              shell: bash

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.version }}

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Copy docker-compose.yml
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "docker-compose.yml"
                  target: "/root/discord/bots/leBot"

            - name: Deploy to production
              uses: appleboy/ssh-action@v1.0.3
              env:
                  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
                  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
                  REGISTRY: ${{ env.REGISTRY }}
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      echo $HARBOR_PASSWORD | docker login $REGISTRY -u $HARBOR_USERNAME --password-stdin
                      cd /root/discord/bots/leBot
                      docker compose pull
                      docker compose up -d
